title: Keane Fernandes
email: keanefern@gmail.com
excerpt_separator: <!--more-->
markdown: kramdown
permalink: /posts/:year/:month/:day/:title
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://keane-fernandes.github.io" # the base hostname & protocol for your site, e.g. http://example.com
github_username:  keane-fernandes
# Build settings
plugins:
  - jekyll-feed